#!/bin/bash

BIN=/usr/bin/chromium

# Cleanup
if ! pgrep chromium > /dev/null;then
  rm -f $HOME/.config/chromium/Singleton*
fi

# Run normally on privved containers or modified un non priv
if grep -q 'Seccomp:.0' /proc/1/status; then
  ${BIN} \
  --ignore-gpu-blocklist \
  --no-first-run \
  --password-store=basic \
  --simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT' \
  --start-maximized \
  --ppapi-flash-path=/opt/libpepflashplayer.so \
  --ppapi-flash-version=34.0.0.137 > /dev/null 2>&1
else
  ${BIN} \
  --ignore-gpu-blocklist \
  --no-first-run \
  --no-sandbox \
  --password-store=basic \
  --simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT' \
  --start-maximized \
  --test-type \
  --ppapi-flash-path=/opt/libpepflashplayer.so \
  --ppapi-flash-version=34.0.0.137 > /dev/null 2>&1
fi