name: Docker images build and push

on:
  push:
    branches: [ "main" ]
    paths:
      - 'actions-time.txt'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Login to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          username: 1lkei
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: Dockerfile
          push: true
          # load: true
          tags: |
            1lkei/chromium-with-flash:latest
          platforms: linux/amd64